version: '3'
services:
  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_USER: gisugo88
      MYSQL_PASSWORD: gisugogisugo88
      MYSQL_DATABASE: kaloriinnhold

  spring-boot-app:
      build:
        context: ./kaloriinnhold
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/kaloriinnhold
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: gisugo88

  react-app:
      build:
        context: ./ui
        dockerfile: Dockerfile
      ports:
        - "3000:80"